import jobiLogo from '../assets/jobi-logo.png';
import jobiLogoBlack from '../assets/jobi-logo-black.png'
import google from '../assets/google.png';
import shipbob from '../assets/shipbob.png';
import dribbble from '../assets/dribbble.png';
import slack from '../assets/slack.png';
import vine from '../assets/vine.png';
import airbnb from '../assets/airbnb.png';
import uiuxdesign from '../assets/ui-ux-design.png';
import development from '../assets/development.png';
import marketing from '../assets/marketing.png';
import telemarketing from '../assets/telemarketing.png';
import accounting from '../assets/accounting.png';
import editing from '../assets/editing.png';
import wordpressDevelopment from '../assets/wordpress-development-small.jpg';
import productDevelopment from '../assets/product-development-small.jpg';
import audioEditing from '../assets/audio-video-editing-small.jpg';
import customerSupport from '../assets/customer-support-small.jpg';
import backArrow from '../assets/back-arrow-icon-black.png';
import nextArrow from '../assets/next-arrow-icon.png';
import error404 from '../assets/error404.jpg';
import profile from '../assets/profile.png';
import bookmark from '../assets/bookmark.png';
import videoPayBtn from '../assets/video-play-button.png';
import account from '../assets/account.png';
import apply from '../assets/apply.png';
import about from '../assets/about.png';
import greyCircle from '../assets/grey-circle.png';
import collabImg from '../assets/bubble-circle-icon.png';
import headerImg from '../assets/people-taking-part-business-event.jpg';
import howItWorksImg from '../assets/let-s-get-started.jpg';
import testimonialsImg from '../assets/testimonials.jpg';
import jobiGuides1 from '../assets/jobi-guides-1.jpg';
import jobiGuides2 from '../assets/jobi-guides-2.jpg';
import jobiGuides3 from '../assets/jobi-guides-3.jpg';
import jobiGuides4 from '../assets/jobi-guides-4.jpg';


export default { jobiLogo, jobiLogoBlack, google, shipbob, dribbble, slack, vine, airbnb, uiuxdesign, development, marketing, telemarketing, accounting,editing, wordpressDevelopment, productDevelopment, audioEditing, customerSupport, backArrow, nextArrow, error404, profile, bookmark, videoPayBtn, account, apply, about, greyCircle, collabImg, headerImg, howItWorksImg, testimonialsImg, jobiGuides1, jobiGuides2, jobiGuides3, jobiGuides4 };