export default 
// [
  // {
  //   uid: "0006",
  //   url: '',
  //   benefits: [
  //     'Health Insurance',
  //     'Paid Time Off',
  //     'Stock Options',
  //     'Training Opportunities',
  //   ],
  //   category: 'Human Resources and Recruitment',
  //   date: '',
  //   employer: '',
  //   facebook: '',
  //   twitter: '',
  //   experienceYears: 1,
  //   expertiseLevel: 'Junior',
  //   description:
  //     "We are looking for a Junior Recruiter to join our growing team. The ideal candidate will have experience sourcing and interviewing candidates, and possess excellent communication and organizational skills.",
  //   title: 'Junior Recruiter',
  //   contractType: 'Full-Time',
  //   keywords: [
  //     'Recruiting',
  //     'Sourcing',
  //     'Interviewing',
  //     'Communication',
  //     'Organization',
  //     'Junior',
  //   ],
  //   location: { city: 'New York', country: 'USA' },
  //   overview:
  //     'We are a growing company looking for a Junior Recruiter to help us find the best talent for our organization. The ideal candidate will be passionate about recruiting and have the drive to succeed.',
  //   requiredSkills: [
  //     'Sourcing',
  //     'Interviewing',
  //     'Communication',
  //     'Organization',
  //     'Junior',
  //   ],
  //   responsibilities: [
  //     'Source and interview candidates for open positions',
  //     'Manage job postings and candidate pipelines',
  //     'Communicate with hiring managers to understand job requirements',
  //     'Maintain candidate database and documentation',
  //     'Provide exceptional candidate experience',
  //   ],
  //   salary: { max: 65000, min: 50000 },
  // }
  // ,
  {
    uid: "0007",
    url: '',
    benefits: [
      'Health Insurance',
      'Paid Time Off',
      'Stock Options',
      'Training Opportunities',
    ],
    category: 'Construction',
    date: '',
    employer: '',
    facebook: '',
    twitter: '',
    experienceYears: 2,
    expertiseLevel: 'Junior',
    description:
      'We are seeking a Junior Construction Manager to join our team. The ideal candidate will have experience in construction management, and possess excellent organizational and communication skills.',
    title: 'Junior Construction Manager',
    contractType: 'Full-Time',
    keywords: [
      'Construction',
      'Management',
      'Organizational',
      'Communication',
      'Junior',
    ],
    location: { city: 'Los Angeles', country: 'USA' },
    overview:
      'We are a leading construction company looking for a Junior Construction Manager to assist in managing our construction projects. The ideal candidate will have a passion for construction and a desire to learn and grow with our team.',
    requiredSkills: [
      'Construction Management',
      'Organizational',
      'Communication',
      'Junior',
    ],
    responsibilities: [
      'Assist in the planning and execution of construction projects',
      'Monitor and manage project timelines and budgets',
      'Communicate with contractors and stakeholders',
      'Ensure project quality and safety standards are met',
      'Provide exceptional client service',
    ],
    salary: { max: 70000, min: 55000 },
  }
// ]
  // {
  //   uid: "0005",
  //   url: 'https://example.com/jobs/backend-developer',
  //   benefits: [
  //     'Competitive salary and benefits package with annual bonuses.',
  //     'Flexible work hours and options to work remotely from anywhere in the world.',
  //     'Opportunities for career growth and advancement.',
  //     'Collaborative and fun work environment with regular team events.',
  //   ],
  //   category: 'Development',
  //   date: '2023-05-04',
  //   employer: 'Zeta Corp',
  //   facebook: 'https://www.facebook.com/zetacorp',
  //   twitter: 'https://twitter.com/zetacorp',
  //   experienceYears: 5,
  //   expertiseLevel: 'Mid-level',
  //   description:
  //     "We are seeking a backend developer to join our team at Zeta Corp. You will work with a team of talented developers to build and maintain our backend systems and services.",
  //   title: 'Backend Developer',
  //   contractType: 'Fulltime',
  //   keywords: [
  //     'backend development',
  //     'web development',
  //     'Python',
  //     'Django',
  //     'REST API',
  //     'PostgreSQL',
  //     'AWS',
  //   ],
  //   location: { city: 'New York', country: 'United States' },
  //   overview:
  //     'Zeta Corp is a fast-growing startup that is building innovative solutions for the digital age.',
  //   requiredSkills: [
  //     'Strong experience with Python and Django.',
  //     'Experience building and consuming REST APIs.',
  //     'Experience with PostgreSQL and AWS.',
  //     'Excellent problem-solving and debugging skills.',
  //     'Ability to work in a fast-paced and collaborative environment.',
  //   ],
  //   responsibilities: [
  //     "Design and implement new backend systems and services.",
  //     'Maintain and improve existing backend code.',
  //     'Collaborate with frontend developers and product managers to define requirements.',
  //     'Write well-documented, modular, and scalable code.',
  //     'Optimize backend systems for performance and scalability.',
  //   ],
  //   salary: { max: 120000, min: 80000 },
  // }

  // {
  //   uid: "0004",
  //   url: "https://example.com/jds190824",
  //   benefits: [
  //     "Health insurance",
  //     "401(k) plan",
  //     "Flexible work schedule",
  //     "Free snacks and drinks",
  //   ],
  //   category: "Data Science",
  //   date: "2023-05-04",
  //   employer: "Acme Analytics",
  //   facebook: "https://facebook.com/acmeanalytics",
  //   twitter: "https://twitter.com/acmeanalytics",
  //   experienceYears: 3,
  //   expertiseLevel: "Senior",
  //   description: "Acme Analytics is looking for a Senior Data Scientist to join our team. The ideal candidate will have a strong background in statistical modeling and machine learning, and experience working with large datasets. The successful candidate will work with our data engineering team to develop models and algorithms that improve our understanding of user behavior and drive business growth.",
  //   title: "Senior Data Scientist",
  //   contractType: "Full-time",
  //   keywords: [
  //     "Data Science",
  //     "Machine Learning",
  //     "Statistical Modeling",
  //     "Python",
  //     "R",
  //     "Big Data",
  //     "Data Mining",
  //     "Business Intelligence",
  //     "Data Visualization",
  //   ],
  //   location: { city: "San Francisco", country: "United States" },
  //   overview: "Acme Analytics is a data-driven company that provides analytics solutions to businesses around the world. We are looking for a Senior Data Scientist to help us build innovative models and algorithms that drive business growth.",
  //   requiredSkills: [
  //     "Strong background in statistical modeling and machine learning",
  //     "Experience working with large datasets",
  //     "Expertise in Python and/or R",
  //     "Ability to communicate complex findings to both technical and non-technical stakeholders",
  //     "Experience with data visualization tools and techniques",
  //   ],
  //   responsibilities: [
  //     "Develop and implement statistical models and machine learning algorithms",
  //     "Work with the data engineering team to develop data pipelines and tools",
  //     "Analyze large datasets to identify patterns and insights",
  //     "Create data visualizations and reports to communicate findings to stakeholders",
  //     "Collaborate with cross-functional teams to drive business growth",
  //   ],
  //   salary: { max: 150000, min: 120000 },
  // }



// [ {
//     uid: "0001",
//     url: 'https://omega.corp/jobs/full-stack-developer',
//     benefits: [
//       'Competitive salary and benefits package with annual bonuses.',
//       'Flexible work hours and options to work remotely from anywhere in the world.',
//       'Opportunities for career growth and advancement.',
//       'Collaborative and fun work environment with regular team events.',
//     ],
//     category: 'Development',
//     date: '2023-03-27',
//     employer: 'Omega Corp',
//     facebook: 'https://www.facebook.com/omegacorp',
//     twitter: 'https://twitter.com/omegacorp',
//     experienceYears: 7,
//     expertiseLevel: 'Senior',
//     description:
//       "As a full-stack developer at Omega Corp, you will be responsible for developing and maintaining the company's web applications and services.",
//     title: 'Full-stack Developer',
//     contractType: 'Fulltime',
//     keywords: [
//       'full-stack development',
//       'web development',
//       'HTML',
//       'CSS',
//       'JavaScript',
//       'React',
//       'Node.js',
//       'MongoDB',
//       'AWS',
//     ],
//     location: { city: 'San Francisco', country: 'United States' },
//     overview:
//       'Omega Corp is looking for a highly skilled full-stack developer to join our team.',
//     requiredSkills: [
//       'Expertise in HTML, CSS, and JavaScript.',
//       'Strong experience with modern web development frameworks such as React and Node.js.',
//       'Experience with MongoDB and AWS.',
//       'Excellent problem-solving and debugging skills.',
//       'Exceptional communication and collaboration skills.',
//     ],
//     responsibilities: [
//       "Develop new features for the company's web applications and services.",
//       'Maintain and improve existing code.',
//       'Collaborate with designers and other developers to implement new features.',
//       'Write well-documented, modular, and scalable code.',
//       'Optimize web applications for performance and scalability.',
//     ],
//     salary: { max: 120000, min: 80000 },
//   },  {
//     uid: "0002",
//     url: 'https://omega.corp/jobs/full-stack-developer',
//     benefits: [
//       'Competitive salary and benefits package with annual bonuses.',
//       'Flexible work hours and options to work remotely from anywhere in the world.',
//       'Opportunities for career growth and advancement.',
//       'Collaborative and fun work environment with regular team events.',
//     ],
//     category: 'Development',
//     date: '2023-03-27',
//     employer: 'Omega Corp',
//     facebook: 'https://www.facebook.com/omegacorp',
//     twitter: 'https://twitter.com/omegacorp',
//     experienceYears: 7,
//     expertiseLevel: 'Senior',
//     description:
//       "As a full-stack developer at Omega Corp, you will be responsible for developing and maintaining the company's web applications and services.",
//     title: 'Front-End Developer',
//     contractType: 'Part Time',
//     keywords: [
//       'full-stack development',
//       'web development',
//       'HTML',
//       'CSS',
//       'JavaScript',
//       'React',
//       'Node.js',
//       'MongoDB',
//       'AWS',
//     ],
//     location: { city: 'Toronto', country: 'Canada' },
//     overview:
//       'Omega Corp is looking for a highly skilled full-stack developer to join our team.',
//     requiredSkills: [
//       'Expertise in HTML, CSS, and JavaScript.',
//       'Strong experience with modern web development frameworks such as React and Node.js.',
//       'Experience with MongoDB and AWS.',
//       'Excellent problem-solving and debugging skills.',
//       'Exceptional communication and collaboration skills.',
//     ],
//     responsibilities: [
//       "Develop new features for the company's web applications and services.",
//       'Maintain and improve existing code.',
//       'Collaborate with designers and other developers to implement new features.',
//       'Write well-documented, modular, and scalable code.',
//       'Optimize web applications for performance and scalability.',
//     ],
//     salary: { max: 120000, min: 80000 },
//   },
// {
//   uid: "0003",
//   url: 'https://example.com/jobs/marketing-coordinator',
//   benefits: [
//     'Flexible work schedule',
//     'Health and dental insurance',
//     '401(k) plan with matching contributions',
//     'Opportunities for career growth',
//   ],
//   category: 'Marketing',
//   date: '2023-05-04',
//   employer: 'Acme Corporation',
//   facebook: 'https://www.facebook.com/acmecorp',
//   twitter: 'https://twitter.com/acmecorp',
//   experienceYears: 2,
//   expertiseLevel: 'Entry-level',
//   description:
//     "We are seeking a Marketing Coordinator to join our team and help support our marketing initiatives. The ideal candidate will have strong communication skills, be detail-oriented, and have experience working in a fast-paced environment.",
//   title: 'Marketing Coordinator',
//   contractType: 'Full-time',
//   keywords: [
//     'marketing',
//     'communication',
//     'campaigns',
//     'events',
//     'social media',
//     'digital',
//     'content',
//     'analytics',
//     'strategy',
//   ],
//   location: { city: 'New York', country: 'United States' },
//   overview:
//     'Acme Corporation is a rapidly growing company in the marketing industry, and we are seeking a Marketing Coordinator to help support our marketing initiatives.',
//   requiredSkills: [
//     'Excellent communication skills',
//     'Experience with digital marketing channels such as social media and email',
//     'Strong organizational and time management skills',
//     'Ability to work independently and in a team environment',
//     'Attention to detail and strong problem-solving skills',
//   ],
//   responsibilities: [
//     'Assist in the development and execution of marketing campaigns',
//     'Coordinate logistics for events and trade shows',
//     'Assist with the creation and distribution of marketing materials',
//     'Maintain marketing database and track analytics',
//     'Conduct market research and competitive analysis',
//   ],
//   salary: { max: 60000, min: 40000 },
// } ]
  
  ;

